vim.opt.encoding      = "utf-8"
vim.opt.fileencodings = { "utf-8", "gbk", "chinese" }
vim.opt.fileencoding  = "utf-8"
vim.opt.background    = "dark"
vim.opt.termguicolors = true
vim.opt.hlsearch      = true
vim.opt.incsearch     = true
vim.opt.backup        = false
vim.opt.undofile      = true
vim.opt.ruler         = true
vim.opt.number        = false
vim.opt.backspace     = { "indent", "eol", "start" }
vim.opt.whichwrap     = "b,s,<,>,[,]"
vim.opt.helplang      = "en"
vim.opt.tabstop       = 4
vim.opt.softtabstop   = 4
vim.opt.shiftwidth    = 4
vim.opt.smarttab      = true
vim.opt.expandtab     = true
vim.opt.showcmd       = true
vim.opt.mouse         = ""
vim.opt.signcolumn    = "yes"
vim.opt.scrolloff     = 8
vim.opt.splitright    = true
vim.opt.splitbelow    = true
vim.opt.guicursor     = ""
